server:
  port: 8080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 
    timeout: 3000
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 5000
logging:
  path: ./blockchain
  file:
    max-size: 100MB
    max-history: 365
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"